// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfRGZGPoX81vtWfB_zIrSkFsC2LiVKaV8',
    appId: '1:530815651440:web:5a09a3eec8cf71996beeb5',
    messagingSenderId: '530815651440',
    projectId: 'spent-time-9b0a1',
    authDomain: 'spent-time-9b0a1.firebaseapp.com',
    storageBucket: 'spent-time-9b0a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Ns06Js9QLk8UI__oA5Vj1PPrpoD47Xo',
    appId: '1:530815651440:android:dc4528386f7959cb6beeb5',
    messagingSenderId: '530815651440',
    projectId: 'spent-time-9b0a1',
    storageBucket: 'spent-time-9b0a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC10O-yrNGOWPLPaCjdCesCOumjxgWPm3s',
    appId: '1:530815651440:ios:473bfa1004ff85956beeb5',
    messagingSenderId: '530815651440',
    projectId: 'spent-time-9b0a1',
    storageBucket: 'spent-time-9b0a1.appspot.com',
    iosBundleId: 'com.example.spentTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC10O-yrNGOWPLPaCjdCesCOumjxgWPm3s',
    appId: '1:530815651440:ios:0c8b2a9df83b2f486beeb5',
    messagingSenderId: '530815651440',
    projectId: 'spent-time-9b0a1',
    storageBucket: 'spent-time-9b0a1.appspot.com',
    iosBundleId: 'com.example.spentTime.RunnerTests',
  );
}
